
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AntecedentesServiceWs", targetNamespace = "http://servicio.sga.gm.com.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AntecedentesServiceWs {


    /**
     * 
     * @return
     *     returns java.util.List<clientews.servicio.Antecedentes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarAntecedentes", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ListarAntecedentes")
    @ResponseWrapper(localName = "listarAntecedentesResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ListarAntecedentesResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/listarAntecedentesRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/listarAntecedentesResponse")
    public List<Antecedentes> listarAntecedentes();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarAntecedentes", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedentes")
    @ResponseWrapper(localName = "registrarAntecedentesResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedentesResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedentesRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedentesResponse")
    public void registrarAntecedentes(
        @WebParam(name = "arg0", targetNamespace = "")
        Antecedentes arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarAntecedentes", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ActualizarAntecedentes")
    @ResponseWrapper(localName = "actualizarAntecedentesResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ActualizarAntecedentesResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/actualizarAntecedentesRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/actualizarAntecedentesResponse")
    public void actualizarAntecedentes(
        @WebParam(name = "arg0", targetNamespace = "")
        Antecedentes arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns clientews.servicio.Antecedentes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarAntecedentesPorId", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentesPorId")
    @ResponseWrapper(localName = "encontrarAntecedentesPorIdResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentesPorIdResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentesPorIdRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentesPorIdResponse")
    public Antecedentes encontrarAntecedentesPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.Antecedentes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarAntecedentesPorArea", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentesPorArea")
    @ResponseWrapper(localName = "encontrarAntecedentesPorAreaResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentesPorAreaResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentesPorAreaRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentesPorAreaResponse")
    public List<Antecedentes> encontrarAntecedentesPorArea(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.Antecedentes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarAntecedentesPorEstudio", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentesPorEstudio")
    @ResponseWrapper(localName = "encontrarAntecedentesPorEstudioResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentesPorEstudioResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentesPorEstudioRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentesPorEstudioResponse")
    public List<Antecedentes> encontrarAntecedentesPorEstudio(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarAntecedenteEstudio", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedenteEstudio")
    @ResponseWrapper(localName = "registrarAntecedenteEstudioResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedenteEstudioResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedenteEstudioRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedenteEstudioResponse")
    public void registrarAntecedenteEstudio(
        @WebParam(name = "arg0", targetNamespace = "")
        AntecedenteEstudio arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarAntecedentesEstudio", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedentesEstudio")
    @ResponseWrapper(localName = "registrarAntecedentesEstudioResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedentesEstudioResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedentesEstudioRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedentesEstudioResponse")
    public void registrarAntecedentesEstudio(
        @WebParam(name = "arg0", targetNamespace = "")
        List<AntecedenteEstudio> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns clientews.servicio.Antecedentes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarAntecedentePorNombre", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentePorNombre")
    @ResponseWrapper(localName = "encontrarAntecedentePorNombreResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentePorNombreResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentePorNombreRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentePorNombreResponse")
    public Antecedentes encontrarAntecedentePorNombre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.Antecedentes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarAntecedentesPorConcepto", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentesPorConcepto")
    @ResponseWrapper(localName = "encontrarAntecedentesPorConceptoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAntecedentesPorConceptoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentesPorConceptoRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/encontrarAntecedentesPorConceptoResponse")
    public List<Antecedentes> encontrarAntecedentesPorConcepto(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarAntecedenteConcepto", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedenteConcepto")
    @ResponseWrapper(localName = "registrarAntecedenteConceptoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedenteConceptoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedenteConceptoRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedenteConceptoResponse")
    public void registrarAntecedenteConcepto(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarAntecedentesConcepto", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarAntecedentesConcepto")
    @ResponseWrapper(localName = "eliminarAntecedentesConceptoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarAntecedentesConceptoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/eliminarAntecedentesConceptoRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/eliminarAntecedentesConceptoResponse")
    public void eliminarAntecedentesConcepto(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarAntecedentesConcepto", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedentesConcepto")
    @ResponseWrapper(localName = "registrarAntecedentesConceptoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarAntecedentesConceptoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedentesConceptoRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/registrarAntecedentesConceptoResponse")
    public void registrarAntecedentesConcepto(
        @WebParam(name = "arg0", targetNamespace = "")
        List<AntecedenteConceptoIds> arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarTodosAntecedentesConcepto", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarTodosAntecedentesConcepto")
    @ResponseWrapper(localName = "eliminarTodosAntecedentesConceptoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarTodosAntecedentesConceptoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/eliminarTodosAntecedentesConceptoRequest", output = "http://servicio.sga.gm.com.mx/AntecedentesServiceWs/eliminarTodosAntecedentesConceptoResponse")
    public void eliminarTodosAntecedentesConcepto(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
