
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AntecedentesServiceImplService", targetNamespace = "http://servicio.sga.gm.com.mx/", wsdlLocation = "http://201.116.155.166:9999/AntecedentesServiceImplService/AntecedentesServiceImpl?wsdl")
public class AntecedentesServiceImplService
    extends Service
{

    private final static URL ANTECEDENTESSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANTECEDENTESSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ANTECEDENTESSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.sga.gm.com.mx/", "AntecedentesServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://201.116.155.166:9999/AntecedentesServiceImplService/AntecedentesServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANTECEDENTESSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ANTECEDENTESSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AntecedentesServiceImplService() {
        super(__getWsdlLocation(), ANTECEDENTESSERVICEIMPLSERVICE_QNAME);
    }

    public AntecedentesServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANTECEDENTESSERVICEIMPLSERVICE_QNAME, features);
    }

    public AntecedentesServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ANTECEDENTESSERVICEIMPLSERVICE_QNAME);
    }

    public AntecedentesServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANTECEDENTESSERVICEIMPLSERVICE_QNAME, features);
    }

    public AntecedentesServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AntecedentesServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AntecedentesServiceWs
     */
    @WebEndpoint(name = "AntecedentesServiceImplPort")
    public AntecedentesServiceWs getAntecedentesServiceImplPort() {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "AntecedentesServiceImplPort"), AntecedentesServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AntecedentesServiceWs
     */
    @WebEndpoint(name = "AntecedentesServiceImplPort")
    public AntecedentesServiceWs getAntecedentesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "AntecedentesServiceImplPort"), AntecedentesServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANTECEDENTESSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ANTECEDENTESSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ANTECEDENTESSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
