
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConceptosServiceImplService", targetNamespace = "http://servicio.sga.gm.com.mx/", wsdlLocation = "http://172.17.200.61:8080/ConceptosServiceImplService/ConceptosServiceImpl?wsdl")
public class ConceptosServiceImplService
    extends Service
{

    private final static URL CONCEPTOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONCEPTOSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CONCEPTOSSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.sga.gm.com.mx/", "ConceptosServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.17.200.61:8080/ConceptosServiceImplService/ConceptosServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONCEPTOSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CONCEPTOSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ConceptosServiceImplService() {
        super(__getWsdlLocation(), CONCEPTOSSERVICEIMPLSERVICE_QNAME);
    }

    public ConceptosServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONCEPTOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConceptosServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CONCEPTOSSERVICEIMPLSERVICE_QNAME);
    }

    public ConceptosServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONCEPTOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConceptosServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConceptosServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConceptosServiceWs
     */
    @WebEndpoint(name = "ConceptosServiceImplPort")
    public ConceptosServiceWs getConceptosServiceImplPort() {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "ConceptosServiceImplPort"), ConceptosServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConceptosServiceWs
     */
    @WebEndpoint(name = "ConceptosServiceImplPort")
    public ConceptosServiceWs getConceptosServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "ConceptosServiceImplPort"), ConceptosServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONCEPTOSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CONCEPTOSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CONCEPTOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
