
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MovimientoCorteServiceWs", targetNamespace = "http://servicio.sga.gm.com.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovimientoCorteServiceWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.MovimientoCorte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerMovimientosDeCorteVespertino", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerMovimientosDeCorteVespertino")
    @ResponseWrapper(localName = "obtenerMovimientosDeCorteVespertinoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerMovimientosDeCorteVespertinoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/MovimientoCorteServiceWs/obtenerMovimientosDeCorteVespertinoRequest", output = "http://servicio.sga.gm.com.mx/MovimientoCorteServiceWs/obtenerMovimientosDeCorteVespertinoResponse")
    public List<MovimientoCorte> obtenerMovimientosDeCorteVespertino(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarMovimientoCorte", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarMovimientoCorte")
    @ResponseWrapper(localName = "registrarMovimientoCorteResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarMovimientoCorteResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/MovimientoCorteServiceWs/registrarMovimientoCorteRequest", output = "http://servicio.sga.gm.com.mx/MovimientoCorteServiceWs/registrarMovimientoCorteResponse")
    public void registrarMovimientoCorte(
        @WebParam(name = "arg0", targetNamespace = "")
        MovimientoCorte arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.MovimientoCorte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerMovimientosDeCorteMatutino", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerMovimientosDeCorteMatutino")
    @ResponseWrapper(localName = "obtenerMovimientosDeCorteMatutinoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ObtenerMovimientosDeCorteMatutinoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/MovimientoCorteServiceWs/obtenerMovimientosDeCorteMatutinoRequest", output = "http://servicio.sga.gm.com.mx/MovimientoCorteServiceWs/obtenerMovimientosDeCorteMatutinoResponse")
    public List<MovimientoCorte> obtenerMovimientosDeCorteMatutino(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
