
package clientews.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PagoOrdenVentaServiceWs", targetNamespace = "http://servicio.sga.gm.com.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PagoOrdenVentaServiceWs {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarPagoOrdenVenta", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarPagoOrdenVenta")
    @ResponseWrapper(localName = "registrarPagoOrdenVentaResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarPagoOrdenVentaResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/PagoOrdenVentaServiceWs/registrarPagoOrdenVentaRequest", output = "http://servicio.sga.gm.com.mx/PagoOrdenVentaServiceWs/registrarPagoOrdenVentaResponse")
    public void registrarPagoOrdenVenta(
        @WebParam(name = "arg0", targetNamespace = "")
        PagoOrdenVenta arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarPagoOrdenVentaPorIdOrdenVenta", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarPagoOrdenVentaPorIdOrdenVenta")
    @ResponseWrapper(localName = "eliminarPagoOrdenVentaPorIdOrdenVentaResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarPagoOrdenVentaPorIdOrdenVentaResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/PagoOrdenVentaServiceWs/eliminarPagoOrdenVentaPorIdOrdenVentaRequest", output = "http://servicio.sga.gm.com.mx/PagoOrdenVentaServiceWs/eliminarPagoOrdenVentaPorIdOrdenVentaResponse")
    public void eliminarPagoOrdenVentaPorIdOrdenVenta(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
