
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaquetesServiceImplService", targetNamespace = "http://servicio.sga.gm.com.mx/", wsdlLocation = "http://201.116.155.166:9999/PaquetesServiceImplService/PaquetesServiceImpl?wsdl")
public class PaquetesServiceImplService
    extends Service
{

    private final static URL PAQUETESSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAQUETESSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PAQUETESSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.sga.gm.com.mx/", "PaquetesServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://201.116.155.166:9999/PaquetesServiceImplService/PaquetesServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAQUETESSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PAQUETESSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PaquetesServiceImplService() {
        super(__getWsdlLocation(), PAQUETESSERVICEIMPLSERVICE_QNAME);
    }

    public PaquetesServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAQUETESSERVICEIMPLSERVICE_QNAME, features);
    }

    public PaquetesServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PAQUETESSERVICEIMPLSERVICE_QNAME);
    }

    public PaquetesServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAQUETESSERVICEIMPLSERVICE_QNAME, features);
    }

    public PaquetesServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaquetesServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaquetesServiceWs
     */
    @WebEndpoint(name = "PaquetesServiceImplPort")
    public PaquetesServiceWs getPaquetesServiceImplPort() {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "PaquetesServiceImplPort"), PaquetesServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaquetesServiceWs
     */
    @WebEndpoint(name = "PaquetesServiceImplPort")
    public PaquetesServiceWs getPaquetesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "PaquetesServiceImplPort"), PaquetesServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAQUETESSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PAQUETESSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PAQUETESSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
