
package clientews.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuariosServiceWs", targetNamespace = "http://servicio.sga.gm.com.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuariosServiceWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "esCorrectoLogin", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EsCorrectoLogin")
    @ResponseWrapper(localName = "esCorrectoLoginResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EsCorrectoLoginResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/UsuariosServiceWs/esCorrectoLoginRequest", output = "http://servicio.sga.gm.com.mx/UsuariosServiceWs/esCorrectoLoginResponse")
    public boolean esCorrectoLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuarios arg0);

}
