
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsuariosServiceImplService", targetNamespace = "http://servicio.sga.gm.com.mx/", wsdlLocation = "http://201.116.155.166:9999/UsuariosServiceImplService/UsuariosServiceImpl?wsdl")
public class UsuariosServiceImplService
    extends Service
{

    private final static URL USUARIOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USUARIOSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USUARIOSSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.sga.gm.com.mx/", "UsuariosServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://201.116.155.166:9999/UsuariosServiceImplService/UsuariosServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USUARIOSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UsuariosServiceImplService() {
        super(__getWsdlLocation(), USUARIOSSERVICEIMPLSERVICE_QNAME);
    }

    public UsuariosServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public UsuariosServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOSSERVICEIMPLSERVICE_QNAME);
    }

    public UsuariosServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public UsuariosServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuariosServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuariosServiceWs
     */
    @WebEndpoint(name = "UsuariosServiceImplPort")
    public UsuariosServiceWs getUsuariosServiceImplPort() {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "UsuariosServiceImplPort"), UsuariosServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuariosServiceWs
     */
    @WebEndpoint(name = "UsuariosServiceImplPort")
    public UsuariosServiceWs getUsuariosServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "UsuariosServiceImplPort"), UsuariosServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw USUARIOSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USUARIOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
