
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VentaConceptosServiceImplService", targetNamespace = "http://servicio.sga.gm.com.mx/", wsdlLocation = "http://localhost:8080/VentaConceptosServiceImplService/VentaConceptosServiceImpl?wsdl")
public class VentaConceptosServiceImplService
    extends Service
{

    private final static URL VENTACONCEPTOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VENTACONCEPTOSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName VENTACONCEPTOSSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.sga.gm.com.mx/", "VentaConceptosServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/VentaConceptosServiceImplService/VentaConceptosServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VENTACONCEPTOSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        VENTACONCEPTOSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public VentaConceptosServiceImplService() {
        super(__getWsdlLocation(), VENTACONCEPTOSSERVICEIMPLSERVICE_QNAME);
    }

    public VentaConceptosServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VENTACONCEPTOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public VentaConceptosServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, VENTACONCEPTOSSERVICEIMPLSERVICE_QNAME);
    }

    public VentaConceptosServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VENTACONCEPTOSSERVICEIMPLSERVICE_QNAME, features);
    }

    public VentaConceptosServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VentaConceptosServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VentaConceptosServiceWs
     */
    @WebEndpoint(name = "VentaConceptosServiceImplPort")
    public VentaConceptosServiceWs getVentaConceptosServiceImplPort() {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "VentaConceptosServiceImplPort"), VentaConceptosServiceWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VentaConceptosServiceWs
     */
    @WebEndpoint(name = "VentaConceptosServiceImplPort")
    public VentaConceptosServiceWs getVentaConceptosServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.sga.gm.com.mx/", "VentaConceptosServiceImplPort"), VentaConceptosServiceWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VENTACONCEPTOSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw VENTACONCEPTOSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return VENTACONCEPTOSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
