
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VentaConceptosServiceWs", targetNamespace = "http://servicio.sga.gm.com.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VentaConceptosServiceWs {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.VentaConceptos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarVentaConceptosPorInstitucionFechas", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptosPorInstitucionFechas")
    @ResponseWrapper(localName = "encontrarVentaConceptosPorInstitucionFechasResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptosPorInstitucionFechasResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptosPorInstitucionFechasRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptosPorInstitucionFechasResponse")
    public List<VentaConceptos> encontrarVentaConceptosPorInstitucionFechas(
        @WebParam(name = "arg0", targetNamespace = "")
        Institucion arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns clientews.servicio.VentaConceptos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarVentaConceptosPorIdPacs", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptosPorIdPacs")
    @ResponseWrapper(localName = "encontrarVentaConceptosPorIdPacsResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptosPorIdPacsResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptosPorIdPacsRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptosPorIdPacsResponse")
    public VentaConceptos encontrarVentaConceptosPorIdPacs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.VentaConceptos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarVentaConceptosPorPacienteFechaEnWorklist", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptosPorPacienteFechaEnWorklist")
    @ResponseWrapper(localName = "encontrarVentaConceptosPorPacienteFechaEnWorklistResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptosPorPacienteFechaEnWorklistResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptosPorPacienteFechaEnWorklistRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptosPorPacienteFechaEnWorklistResponse")
    public List<VentaConceptos> encontrarVentaConceptosPorPacienteFechaEnWorklist(
        @WebParam(name = "arg0", targetNamespace = "")
        Pacientes arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2);

    /**
     * 
     * @return
     *     returns java.util.List<clientews.servicio.VentaConceptos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarTodosVentaConceptos", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ListarTodosVentaConceptos")
    @ResponseWrapper(localName = "listarTodosVentaConceptosResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ListarTodosVentaConceptosResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/listarTodosVentaConceptosRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/listarTodosVentaConceptosResponse")
    public List<VentaConceptos> listarTodosVentaConceptos();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarIdOrdenVenta", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ActualizarIdOrdenVenta")
    @ResponseWrapper(localName = "actualizarIdOrdenVentaResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ActualizarIdOrdenVentaResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/actualizarIdOrdenVentaRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/actualizarIdOrdenVentaResponse")
    public boolean actualizarIdOrdenVenta();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.VentaConceptos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontarVentaConceptosPorIdOrdenVenta", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontarVentaConceptosPorIdOrdenVenta")
    @ResponseWrapper(localName = "encontarVentaConceptosPorIdOrdenVentaResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontarVentaConceptosPorIdOrdenVentaResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontarVentaConceptosPorIdOrdenVentaRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontarVentaConceptosPorIdOrdenVentaResponse")
    public List<VentaConceptos> encontarVentaConceptosPorIdOrdenVenta(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.VentaConceptos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarAgendadosPorAreaEquipoDicomFecha", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAgendadosPorAreaEquipoDicomFecha")
    @ResponseWrapper(localName = "encontrarAgendadosPorAreaEquipoDicomFechaResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAgendadosPorAreaEquipoDicomFechaResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarAgendadosPorAreaEquipoDicomFechaRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarAgendadosPorAreaEquipoDicomFechaResponse")
    public List<VentaConceptos> encontrarAgendadosPorAreaEquipoDicomFecha(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.VentaConceptos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarAgendadosPorAreaEquipoDicomFechaInstitucion", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAgendadosPorAreaEquipoDicomFechaInstitucion")
    @ResponseWrapper(localName = "encontrarAgendadosPorAreaEquipoDicomFechaInstitucionResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarAgendadosPorAreaEquipoDicomFechaInstitucionResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarAgendadosPorAreaEquipoDicomFechaInstitucionRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarAgendadosPorAreaEquipoDicomFechaInstitucionResponse")
    public List<VentaConceptos> encontrarAgendadosPorAreaEquipoDicomFechaInstitucion(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Long arg3);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarVentaConceptos", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarVentaConceptos")
    @ResponseWrapper(localName = "registrarVentaConceptosResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarVentaConceptosResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/registrarVentaConceptosRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/registrarVentaConceptosResponse")
    public void registrarVentaConceptos(
        @WebParam(name = "arg0", targetNamespace = "")
        VentaConceptos arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarVentaConceptosList", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarVentaConceptosList")
    @ResponseWrapper(localName = "registrarVentaConceptosListResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.RegistrarVentaConceptosListResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/registrarVentaConceptosListRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/registrarVentaConceptosListResponse")
    public void registrarVentaConceptosList(
        @WebParam(name = "arg0", targetNamespace = "")
        List<VentaConceptos> arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns clientews.servicio.VentaConceptos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarVentaConceptoPorOrdenVentaConceptoHoraAsignado", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptoPorOrdenVentaConceptoHoraAsignado")
    @ResponseWrapper(localName = "encontrarVentaConceptoPorOrdenVentaConceptoHoraAsignadoResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptoPorOrdenVentaConceptoHoraAsignadoResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptoPorOrdenVentaConceptoHoraAsignadoRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptoPorOrdenVentaConceptoHoraAsignadoResponse")
    public VentaConceptos encontrarVentaConceptoPorOrdenVentaConceptoHoraAsignado(
        @WebParam(name = "arg0", targetNamespace = "")
        OrdenVenta arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Conceptos arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns clientews.servicio.VentaConceptos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarVentaConceptosPorId", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptosPorId")
    @ResponseWrapper(localName = "encontrarVentaConceptosPorIdResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarVentaConceptosPorIdResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptosPorIdRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarVentaConceptosPorIdResponse")
    public VentaConceptos encontrarVentaConceptosPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarVentaConceptos", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarVentaConceptos")
    @ResponseWrapper(localName = "eliminarVentaConceptosResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarVentaConceptosResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/eliminarVentaConceptosRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/eliminarVentaConceptosResponse")
    public void eliminarVentaConceptos(
        @WebParam(name = "arg0", targetNamespace = "")
        VentaConceptos arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarNumeroVentaConceptosPorEquipoFechaHora", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarNumeroVentaConceptosPorEquipoFechaHora")
    @ResponseWrapper(localName = "encontrarNumeroVentaConceptosPorEquipoFechaHoraResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EncontrarNumeroVentaConceptosPorEquipoFechaHoraResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarNumeroVentaConceptosPorEquipoFechaHoraRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/encontrarNumeroVentaConceptosPorEquipoFechaHoraResponse")
    public Long encontrarNumeroVentaConceptosPorEquipoFechaHora(
        @WebParam(name = "arg0", targetNamespace = "")
        EquipoDicom arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.VentaConceptos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAgendadosByFecha", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.FindAgendadosByFecha")
    @ResponseWrapper(localName = "findAgendadosByFechaResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.FindAgendadosByFechaResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/findAgendadosByFechaRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/findAgendadosByFechaResponse")
    public List<VentaConceptos> findAgendadosByFecha(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarVentaConceptos", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ActualizarVentaConceptos")
    @ResponseWrapper(localName = "actualizarVentaConceptosResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ActualizarVentaConceptosResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/actualizarVentaConceptosRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/actualizarVentaConceptosResponse")
    public void actualizarVentaConceptos(
        @WebParam(name = "arg0", targetNamespace = "")
        VentaConceptos arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarVentaConceptosPorIdOrdenVenta", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarVentaConceptosPorIdOrdenVenta")
    @ResponseWrapper(localName = "eliminarVentaConceptosPorIdOrdenVentaResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.EliminarVentaConceptosPorIdOrdenVentaResponse")
    @Action(input = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/eliminarVentaConceptosPorIdOrdenVentaRequest", output = "http://servicio.sga.gm.com.mx/VentaConceptosServiceWs/eliminarVentaConceptosPorIdOrdenVentaResponse")
    public void eliminarVentaConceptosPorIdOrdenVenta(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
