/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;


import javax.swing.JOptionPane;


/**
 *
 * @author alanm
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        
        
    }

     private void cerrar() {
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?", "Salir", dialog);

        if (result == 0) {
            System.exit(0);
        } else {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPagar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnAgendar = new javax.swing.JButton();
        btnCortes = new javax.swing.JButton();
        btnEntradas = new javax.swing.JButton();
        btnUrgencias = new javax.swing.JButton();
        btnReagendar = new javax.swing.JButton();
        btnCancelaciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPagar.setBackground(new java.awt.Color(204, 204, 204));
        btnPagar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(0, 0, 51));
        btnPagar.setText("Pagar orden");
        btnPagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 40));

        btnConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        btnConfirmar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(0, 0, 51));
        btnConfirmar.setText("Confirmar cita");
        btnConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 40));

        btnAgendar.setBackground(new java.awt.Color(204, 204, 204));
        btnAgendar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAgendar.setForeground(new java.awt.Color(0, 0, 51));
        btnAgendar.setText("Agendar");
        btnAgendar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 40));

        btnCortes.setBackground(new java.awt.Color(204, 204, 204));
        btnCortes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCortes.setForeground(new java.awt.Color(0, 0, 51));
        btnCortes.setText("Cortes");
        btnCortes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnCortes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 40));

        btnEntradas.setBackground(new java.awt.Color(204, 204, 204));
        btnEntradas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEntradas.setForeground(new java.awt.Color(0, 0, 51));
        btnEntradas.setText("Entradas/salidas");
        btnEntradas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradasActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, 40));

        btnUrgencias.setBackground(new java.awt.Color(204, 204, 204));
        btnUrgencias.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUrgencias.setForeground(new java.awt.Color(0, 0, 51));
        btnUrgencias.setText("Urgencias");
        btnUrgencias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnUrgencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 120, 40));

        btnReagendar.setBackground(new java.awt.Color(204, 204, 204));
        btnReagendar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReagendar.setForeground(new java.awt.Color(0, 0, 51));
        btnReagendar.setText("Reagendar");
        btnReagendar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnReagendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 40));

        btnCancelaciones.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelaciones.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCancelaciones.setForeground(new java.awt.Color(0, 0, 51));
        btnCancelaciones.setText("Cancelaciones");
        btnCancelaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnCancelaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 120, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOLA, BIENVENIDO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 300, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu();
                menu.setVisible(true);
                menu.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgendar;
    public javax.swing.JButton btnCancelaciones;
    public javax.swing.JButton btnConfirmar;
    public javax.swing.JButton btnCortes;
    public javax.swing.JButton btnEntradas;
    public javax.swing.JButton btnPagar;
    public javax.swing.JButton btnReagendar;
    public javax.swing.JButton btnUrgencias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
